Upsampling using Conv2DTranspose (reverses downsampling for Autoencoders)

In [2]:
from keras.models import Sequential
from keras.layers import UpSampling2D
import numpy as np
model = Sequential()
#add upsampling layer
model.add(UpSampling2D())

#create a 2x2 array simulating pixels
X = np.array([[1, 2],
			 [3, 4]])
print(X)


[[1 2]
 [3 4]]


In [3]:
#reshape input
X = X.reshape((1, 2, 2, 1))

In [5]:
model = Sequential()
#takes in 2x2 grayscale images
model.add(UpSampling2D(input_shape=(2, 2, 1)))
#print model attribs
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
up_sampling2d_2 (UpSampling2 (None, 4, 4, 1)           0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________


In [7]:
#make a prediction using the model to upscale input
yhat = model.predict(X)
print(yhat)

[[[[1.]
   [1.]
   [2.]
   [2.]]

  [[1.]
   [1.]
   [2.]
   [2.]]

  [[3.]
   [3.]
   [4.]
   [4.]]

  [[3.]
   [3.]
   [4.]
   [4.]]]]


In [9]:
#reshape so it's more aesthetic to print
yhat = yhat.reshape((4, 4))
# summarize output
print(yhat)

#successfully upscaled the 2x2 array

[[1. 1. 2. 2.]
 [1. 1. 2. 2.]
 [3. 3. 4. 4.]
 [3. 3. 4. 4.]]


Create a generative model (unsupervised generation of new samples)

In [12]:
from keras.layers import Dense
from keras.layers import Reshape
model = Sequential()
#input dim - 100. Output is 128 5x5 images
model.add(Dense(128 * 5 * 5, input_dim=100))
#reshape vector into 5x5 feature maps
model.add(Reshape((5, 5, 128)))

In [14]:
#upsample. Go from 128 5x5 to 1 10x10 feature map
model.add(UpSampling2D())

In [16]:
from keras.layers import Conv2D
#output a single image instead of a feature map
model.add(Conv2D(1, (3,3), padding='same'))

In [17]:
model.summary()

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 3200)              323200    
_________________________________________________________________
reshape (Reshape)            (None, 5, 5, 128)         0         
_________________________________________________________________
up_sampling2d_3 (UpSampling2 (None, 10, 10, 128)       0         
_________________________________________________________________
up_sampling2d_4 (UpSampling2 (None, 20, 20, 128)       0         
_________________________________________________________________
conv2d (Conv2D)              (None, 20, 20, 1)         1153      
Total params: 324,353
Trainable params: 324,353
Non-trainable params: 0
_________________________________________________________________


In [23]:
#predict using 100 random ints in an array
X = np.random.randint(1,10,100)
X = np.expand_dims(X, axis=0)

yhat = model.predict(X)
print (yhat)

[[[[ 6.76944256e-02]
   [-1.20722270e+00]
   [-1.20722282e+00]
   [-1.85978222e+00]
   [-1.67274475e+00]
   [-4.40990806e-01]
   [-4.40990567e-01]
   [ 5.90594709e-01]
   [-2.47300625e-01]
   [-1.58021688e-01]
   [-1.58021629e-01]
   [-2.00496507e+00]
   [-6.17411017e-01]
   [-1.22722912e+00]
   [-1.22722912e+00]
   [ 3.43025923e-01]
   [-1.30104196e+00]
   [-6.17671728e-01]
   [-6.17671609e-01]
   [-9.98104036e-01]]

  [[-4.44012046e-01]
   [-1.52921128e+00]
   [-1.52921200e+00]
   [-3.55264878e+00]
   [-2.99086523e+00]
   [-2.02968812e+00]
   [-2.02968788e+00]
   [ 6.05193019e-01]
   [ 6.15372777e-01]
   [ 2.59345055e-01]
   [ 2.59345055e-01]
   [-1.94079089e+00]
   [-1.64405537e+00]
   [-1.04588306e+00]
   [-1.04588306e+00]
   [-4.02389407e-01]
   [-9.31493521e-01]
   [-1.85589623e+00]
   [-1.85589612e+00]
   [-1.66684699e+00]]

  [[-4.44012195e-01]
   [-1.52921128e+00]
   [-1.52921176e+00]
   [-3.55264902e+00]
   [-2.99086547e+00]
   [-2.02968788e+00]
   [-2.02968788e+00]
   [ 6.05

Intro to the Conv2DTranspose Layer

In [27]:
from keras.layers import Conv2DTranspose
#input data 2x2 array
X = np.array([[1, 2],
			 [3, 4]])
print(X)
#reshape
X = X.reshape((1, 2, 2, 1))

model = Sequential()
model.add(Conv2DTranspose(1, (1,1), strides=(2,2), input_shape=(2, 2, 1)))
#print summary
model.summary()
#define weights (not functional)
weights = [np.array([[[[1]]]]), np.array([0])]
#store weights
model.set_weights(weights)
#predict
yhat = model.predict(X)
#make printing aesthetic w reshaping
yhat = yhat.reshape((4, 4))
print(yhat)

[[1 2]
 [3 4]]
Model: "sequential_8"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_transpose_2 (Conv2DTr (None, 4, 4, 1)           2         
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________
[[1. 0. 2. 0.]
 [0. 0. 0. 0.]
 [3. 0. 4. 0.]
 [0. 0. 0. 0.]]


Upsampling using Conv2DTranspose and generative model

In [28]:
from keras.layers import Conv2DTranspose
from keras.layers import Conv2D
model = Sequential()
#input dim = 1D vector of 100 size; output - 128 5x5 instances
model.add(Dense(128 * 5 * 5, input_dim=100))
#reshape input into output shape
model.add(Reshape((5, 5, 128)))
#double input into 10x10 feature map
model.add(Conv2DTranspose(1, (3,3), strides=(2,2), padding='same'))
model.summary()

Model: "sequential_9"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2 (Dense)              (None, 3200)              323200    
_________________________________________________________________
reshape_1 (Reshape)          (None, 5, 5, 128)         0         
_________________________________________________________________
conv2d_transpose_3 (Conv2DTr (None, 10, 10, 1)         1153      
Total params: 324,353
Trainable params: 324,353
Non-trainable params: 0
_________________________________________________________________
